In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [3]:
a1=np.array([1,2,3,4,5])
print(a1)

[1 2 3 4 5]


In [4]:
type(a1)


numpy.ndarray

In [5]:
a1.shape

(5,)

In [6]:
a1.size

5

In [8]:
a2=np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [9]:
type(a2)

numpy.ndarray

In [10]:
a2.shape

(2, 3)

In [11]:
a2.size

6

In [12]:
a2.ndim

2

In [17]:
a3=np.array([[[1,2,3],[3,4,5],[6,7,8]]])
print(a3)

[[[1 2 3]
  [3 4 5]
  [6 7 8]]]


In [18]:
type(a3)

numpy.ndarray

In [19]:
a3.shape

(1, 3, 3)

In [20]:
a3.size

9

In [21]:
a3.ndim

3

ZERO ARRAYS

In [23]:
z1=np.zeros(3)
print(z1)

[0. 0. 0.]


In [25]:
z1=np.zeros(3,dtype=int)
z1

array([0, 0, 0])

In [26]:
z1.shape

(3,)

In [27]:
z1.size

3

In [28]:
z1.ndim


1

In [30]:
type(z1)

numpy.ndarray

In [31]:
z2=np.zeros((3,4))
z2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
z2=np.zeros((3,4),dtype=int)
z2


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [33]:
type(z2)

numpy.ndarray

In [34]:
z2.size

12

In [35]:
z2.shape

(3, 4)

In [36]:
z2.ndim

2

In [37]:
z3=np.zeros((2,3,4))
z3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [38]:
type(z3)

numpy.ndarray

In [39]:
z3.size

24

In [40]:
z3.shape

(2, 3, 4)

In [41]:
z3.ndim

3

In [43]:
z3=np.zeros((2,3,4),dtype=int)
z3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

1D array

In [46]:
a1=np.ones(3)
a1

array([1., 1., 1.])

In [47]:
a1=np.ones(3,dtype=int)
a1

array([1, 1, 1])

In [48]:
a1.shape


(3,)

In [49]:
a1.size

3

In [50]:
a1.ndim

1

In [51]:
type(a1)

numpy.ndarray

In [54]:
a2=np.ones((2,3))
a2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
a2=np.ones((2,3),dtype=int)
a2


array([[1, 1, 1],
       [1, 1, 1]])

In [57]:
type(a2)

numpy.ndarray

In [58]:
a2.size

6

In [59]:
a2.shape


(2, 3)

In [60]:
a2.ndim

2

In [67]:
a2=np.ones(((4,3,4)))
a2

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [68]:
a2=np.ones((4,3,4),dtype=int)
a2


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [69]:
type(a2)

numpy.ndarray

In [70]:
a2.size


48

In [71]:
a2.shape

(4, 3, 4)

In [72]:
a2.ndim

3

In [73]:
f1=np.full(3,9)
f1

array([9, 9, 9])

In [75]:
f1=np.full(3,9,dtype=float)
f1

array([9., 9., 9.])

In [76]:
f2=np.full((2,3),9)
f2

array([[9, 9, 9],
       [9, 9, 9]])

In [77]:
f3=np.full((4,2,3),10)
f3

array([[[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]]])